Modify color setting for two plots
UofT-CS-Group/CSC110-Final-Project pull request #36
Opened 2021-12-05 10:21 UTC by CharlotteChenyy

2021-12-05 17:53 UTC, ScottCTD requested changes
GREAT

but still some changes needed

2021-12-05 17:53 UTC, ScottCTD commented on Application/gui_main.py
> +        self.initialization_button.setStatusTip('Initialize/Re-initialize the data')
先不管menu

所有其他的widget的status tip都该放在`MainWindowUI`类里

后面的同理

另外就是不止status tip，还有个东西叫tool tip，那个其实更好看更提示性，建议也加上，当然，也是在UI类里，至于menu咋搞等这个和ray的merge了我稍微改一下

2021-12-05 17:53 UTC, ScottCTD commented on Application/gui_main.py
> +        color = QColorDialog.getColor().name()
Good

但是建议在`gui_utils.py`里面开一个新的类叫类似`StandardColorDialog`的然后继承`QColorDialog`，在子类的initializer里`set_font()`

后面的TextDialog啥的同理

2021-12-05 18:33 UTC, CharlotteChenyy commented on Application/gui_main.py
> +        self.initialization_button.setStatusTip('Initialize/Re-initialize the data')
okay

2021-12-05 18:35 UTC, ScottCTD commented on Application/gui_main.py
> +        self.initialization_button.setStatusTip('Initialize/Re-initialize the data')
oh my god

大佬又在熬夜肝代码

2021-12-05 18:36 UTC, CharlotteChenyy commented on Application/gui_main.py
> +        self.initialization_button.setStatusTip('Initialize/Re-initialize the data')
救命不是哈哈哈哈 刚刚在画画

2021-12-05 18:43 UTC, CharlotteChenyy commented on Application/gui_main.py
> +        color = QColorDialog.getColor().name()
那在gui_utils.py开完这个之后 是要在MainWindowUI里新搞个instance attribute 然后再传到function里 还是在下面的function里直接搞?

2021-12-06 05:08 UTC, ScottCTD commented on Application/gui_main.py
> +        color = QColorDialog.getColor().name()
这个dialog是一次性的，直接在方法里创建新对象就行

2021-12-06 06:05 UTC, CharlotteChenyy commented on Application/gui_main.py
> +        color = QColorDialog.getColor().name()
了解了 那我再改一下~

2021-12-06 22:50 UTC, ScottCTD commented
@CharlotteChenyy  Pls review #38 when you are available

2021-12-07 19:05 UTC, merged