Refactor report
UofT-CS-Group/CSC110-Final-Project pull request #44
Opened 2021-12-10 06:42 UTC by ScottCTD

- I didn't check the grammar.
- I want to sleep.

2021-12-10 22:04 UTC, Lei-Tin requested changes
ok 喷的有点多，大部分都是可以直接复制粘贴把我的换上去

你到时候判断觉得我的好还是原本的好，直接选择 Accept Left or Right 就好

2021-12-10 22:04 UTC, Lei-Tin commented on Report/final_report.tex
> +        To investigate the root of the problem, we analyzed the running time of our algorithms but it turned out that the running time was good ($\bigO(n)$).
> ...we analyzed the running time of our algorithms but it turned out that the running time was good ($\bigO(n)$). 

...we analyzed the running time of our algorithms, but it turned out that the running time was fairly decent ($\bigO(n)$).

2021-12-10 22:04 UTC, Lei-Tin commented on Report/final_report.tex
> +        Then, we used \verb|time| module and divided the codes into many piece of codes to calculate the real times each piece took. Finally, we found that the root of the evil is actually the \verb|
> Then, we used \verb|time| module and divided the codes into segments to calculate the real times each piece took. Finally, we found that the root cause of this issue is actually from the \verb|Matplotlib#Canvas.draw()| function call. But another issue arose along with this discovery, we cannot modify the code from \verb|matplotlib| to make it faster.

2021-12-10 22:04 UTC, Lei-Tin commented on Report/final_report.tex
> +        This largely improve the FPS and now the cross-hair is very smooth.
> This largely improve the FPS and now the cross-hair is very smooth.

This largely improved the frame rate and now the cross-hair is rendered very smoothly.

2021-12-10 22:04 UTC, Lei-Tin commented on Report/final_report.tex
> +    \subsection{The Future}
我觉得叫 Next Steps 好一点

The future sounds so stupid ngl hahahahahahaha

2021-12-11 02:39 UTC, ScottCTD commented on Report/final_report.tex
> -    The purpose of this sub-sub-section is to ensure that our application will run on any machine with our predetermined datasets.
我这里写的比较泛，没有具体说是sorting algorithm，所以我觉得说compare不太合适

2021-12-11 02:44 UTC, ScottCTD commented on Report/final_report.tex
> +        \item And many more details...
啊这 这个就是个总览吧，真要放细节更没必要吧

2021-12-11 02:45 UTC, ScottCTD commented on Report/final_report.tex
> +    \subsubsection{Utilities}
No

Utilities是GUI的Utilities，在这个GUI大类下面，被主GUI用了

2021-12-11 02:46 UTC, ScottCTD commented on Report/final_report.tex
> +        \item ...
不用

2021-12-11 02:46 UTC, ScottCTD commented on Report/final_report.tex
> +        \item \verb|StandardMenuBar|: A standard menu bar.
嗯。。我稍微加点

2021-12-11 02:58 UTC, ScottCTD commented on Report/final_report.tex
> +        If we want to display a progress bar monitoring the progress of something like initialization, we need three tasks to be performed simultaneously, or asynchronously:
为了引出多线程，我觉得写上好

毕竟是计算机作业，多用点计算机词汇233

2021-12-11 03:28 UTC, Lei-Tin commented on Report/final_report.tex
> +        \item And many more details...
No I meant

要不要直接把这行删掉
丢这边好像也没什么用

你可以把前面改成, Functionalities, such as but not limited to:

2021-12-11 03:29 UTC, Lei-Tin commented on Report/final_report.tex
> +        \item ...
那你还不去掉这个"..."

2021-12-11 03:30 UTC, Lei-Tin commented on Report/final_report.tex
> +        If we want to display a progress bar monitoring the progress of something like initialization, we need three tasks to be performed simultaneously, or asynchronously:
Hmm
因为 Asynchronous 跟 Simulatenous 意思一样，有点 redundant

还有我上面第二个其实是改了语法 + 删掉 Asynchronous

2021-12-11 04:30 UTC, ScottCTD commented on Report/final_report.tex
> +        If we want to display a progress bar monitoring the progress of something like initialization, we need three tasks to be performed simultaneously, or asynchronously:
ok

2021-12-11 04:44 UTC, Lei-Tin commented on Report/final_report.tex
> -    The purpose of this sub-sub-section is to ensure that our application will run on any machine with our predetermined datasets.
ok, make sense
那就留这样吧

2021-12-11 04:51 UTC, Lei-Tin approved these changes
Okai，再看了一遍没看到什么大问题
我明天无聊了，有空了再瞅瞅 :3

就是 for some, idk why you marked discussion as resolve but you didn't commit a change to fix it
目前只发现了[这个](https://github.com/UofT-CS-Group/CSC110-Final-Project/pull/44/files#diff-3250e24ae1ef9b1678812561f78c7ea59003b34e33310a3a026765af20a45cd6R202)

有请我们的下一位 Reviewer！@CharlotteChenyy 
我先去躺平了哈哈哈哈哈哈哈哈哈

2021-12-11 04:51 UTC, Lei-Tin commented on Report/final_report.tex
> +    \subsubsection{Utilities}
oh shit I'm blind
I thought it was Utilities as an individual section
没看到 subsub section，那没事了

2021-12-11 04:56 UTC, Lei-Tin commented on Report/final_report.tex
> +        \item Our application crashes all day, all night, 24 * 7, non-stop. Making us want to drop out of CSC110. But nevertheless, we still overcame the difficulties and produced a "Functioning" app
btw 这个哈哈哈哈哈哈哈哈哈啊哈哈
看看 Charlotte 跟 Alysssa 要不要留吧哈哈哈哈哈哈哈哈哈

超级 informal but pretty fun 哈哈哈哈哈

2021-12-11 04:58 UTC, Lei-Tin commented on Report/final_report.tex
> +    Or you could clone our repository and everything will be right in the correct place. TODO: Add github.
GitHub link: 
https://github.com/UofT-CS-Group/CSC110-Final-Project

ssh: 
git@github.com:UofT-CS-Group/CSC110-Final-Project.git

idk 你要放哪个, 如果是link你应该已经放了，so 很有可能是我不知道我自己在干嘛

2021-12-11 04:59 UTC, Lei-Tin commented on Report/final_report.tex
> +    If our application failed to download all \textbf{required} resources, please download this compressed file and unzip it in the same directory as the \verb|main.py|. Make sure that the \verb|reso
Maybe use [USend](https://send.utoronto.ca/)

This is the one recommended in the submission webpage

2021-12-11 04:59 UTC, Lei-Tin commented on Report/final_report.tex
> +    If our application failed to download all \textbf{required} resources, please download this compressed file and unzip it in the same directory as the \verb|main.py|. Make sure that the \verb|reso
This one is available for 14 days, maybe we can upload it on Dec 12 or 13

2021-12-11 05:33 UTC, ScottCTD commented on Report/final_report.tex
> +        \item ...
我的意思是留着，但是不用补充其他的，因为确实还有别的

2021-12-11 05:34 UTC, ScottCTD commented on Report/final_report.tex
> +        \item Our application crashes all day, all night, 24 * 7, non-stop. Making us want to drop out of CSC110. But nevertheless, we still overcame the difficulties and produced a "Functioning" app
留

2021-12-11 05:37 UTC, Lei-Tin commented on Report/final_report.tex
> +        \item ...
Hmm, 我觉得这种列举但是不全说的在最后加个 "And more" 听起来就不太对

你可以参考[上面](https://github.com/UofT-CS-Group/CSC110-Final-Project/pull/44/files#diff-3250e24ae1ef9b1678812561f78c7ea59003b34e33310a3a026765af20a45cd6R177)那个做法，改成 "the following classes, such as but not limited to: "

2021-12-11 05:48 UTC, ScottCTD commented on Report/final_report.tex
> +    If our application failed to download all \textbf{required} resources, please download this compressed file and unzip it in the same directory as the \verb|main.py|. Make sure that the \verb|reso
Google Drive public link

No time limit if I were not wrong

2021-12-11 05:58 UTC, Lei-Tin commented on Report/final_report.tex
> +    If our application failed to download all \textbf{required} resources, please download this compressed file and unzip it in the same directory as the \verb|main.py|. Make sure that the \verb|reso
That would work too, 但是要确保有让任何人都能打开的 权限

2021-12-11 06:25 UTC, CharlotteChenyy reviewed
我comment的可加可不加 我不知道合不合适lol

2021-12-11 06:25 UTC, CharlotteChenyy commented on Report/final_report.tex
>          \item Customizable line color, style, and marker.
Maybe add: Some shortcuts of actions

2021-12-11 06:25 UTC, CharlotteChenyy commented on Report/final_report.tex
> +            You should be able to set the start and end dates for the plot, pan and zoom on the plot, select countries and plot the result again, and utilize the menu bar for more customizable config
> ...and utilize the menu bar for more customizable configurations.

...and utilize the menu bar for more customizable configurations or even save the plot.

2021-12-11 06:25 UTC, CharlotteChenyy commented on Report/final_report.tex
> +        \item We haven't tested our application on any Linux distributions.
我今天可以晚些时候在虚拟机上的linux系统跑一下 然后再来comment

2021-12-11 06:25 UTC, CharlotteChenyy commented on Report/final_report.tex
> +        \item Our application crashes all day, all night, 24 * 7, non-stop. Making us want to drop out of CSC110. But nevertheless, we still overcame the difficulties and produced a "Functioning" app
lololol

2021-12-11 06:26 UTC, CharlotteChenyy commented on Report/final_report.tex
> +        \item Our application crashes all day, all night, 24 * 7, non-stop. Making us want to drop out of CSC110. But nevertheless, we still overcame the difficulties and produced a "Functioning" app
lololol

2021-12-11 06:36 UTC, ScottCTD commented on Report/final_report.tex
> +        \item We haven't tested our application on any Linux distributions.
2333我在WSL跑不起来，不过用虚拟机估计可以

2021-12-11 17:31 UTC, CharlotteChenyy commented
![image](https://user-images.githubusercontent.com/60980117/145685926-814fa444-0294-441e-8502-03623d50b23a.png)
linux似乎跑不起来 然后我在另一个windows里跑也是同样的报错信息

2021-12-11 18:19 UTC, CharlotteChenyy commented
咱们还考虑多平台吗 感觉不满足python3.6+的兼容性是不是就别考虑多平台了 很多发行版源还是3.7 3.8的 自行编译试过了 x-server会崩

2021-12-11 18:22 UTC, ScottCTD commented
我不想考虑 现在最正常的是windows + python3.10

直接report里说我们只这样测试过就行

2021-12-11 21:16 UTC, Lei-Tin commented
> 我不想考虑 现在最正常的是windows + python3.10
> 
> 直接report里说我们只这样测试过就行

Ye，可以的

实际情况就是 Win 10 + Python 3.10 (最稳定)
Or MacOS Monterey + Intel + Python 3.10
Or MacOS Big Sur + M1 + Rosetta Terminal + Python 3.9.6 + A ton of compatibility configurations

2021-12-12 05:01 UTC, CharlotteChenyy approved these changes

2021-12-12 05:35 UTC, ScottCTD commented
ok 都approve，merge里，有问题直接新pr就行

2021-12-12 05:36 UTC, merged